// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJHi1a03TVNL3RlttqoBsOwMYN6KjUWEk',
    appId: '1:565170721970:web:7f13119875d91d6575e5ab',
    messagingSenderId: '565170721970',
    projectId: 'startup-expense-tracker-3df6b',
    authDomain: 'startup-expense-tracker-3df6b.firebaseapp.com',
    storageBucket: 'startup-expense-tracker-3df6b.firebasestorage.app',
    measurementId: 'G-6LG6H5D5G2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXeAS_EzI0p_mujS-PUVMmO_e5Ke60o1k',
    appId: '1:565170721970:android:fdab53daefaaf19675e5ab',
    messagingSenderId: '565170721970',
    projectId: 'startup-expense-tracker-3df6b',
    storageBucket: 'startup-expense-tracker-3df6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOuqpjZHnGrziCssyHkhjxnhxZPXDsXYg',
    appId: '1:565170721970:ios:ee60d9ec99a5244f75e5ab',
    messagingSenderId: '565170721970',
    projectId: 'startup-expense-tracker-3df6b',
    storageBucket: 'startup-expense-tracker-3df6b.firebasestorage.app',
    iosBundleId: 'com.example.startupExpenseTracker',
  );
}
